### PR TITLE
Use node20

### PR DESCRIPTION
**Pull request by iChebbi**
With the [deprecation notice](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) from Github due to Node 16 reaching EOF , i'm updating the action configuration to use Node 20 instead

### CODE REVIEW

**Comment by na-jakobs** [comment]
@wms @sammcj @eilinora Can you please update the action? 🙏

**Review by sammcj — APPROVED** [review]

**Comment by sammcj** [comment]
Nice, thanks for the reminder!

**Comment by sammcj** [comment]
looking at their Github - I suspect they're no longer active and that this Action should be considered unmaintained.

**Comment by wms** [comment]
Still active, but dont' have much time for public-facing work these days :(

This looks good though.

**Comment by iChebbi** [comment]
@wms Thanks for merging 
Can we expect a new release soon?

**Comment by wms** [comment]
@iChebbi [Yessir!](https://github.com/fountainhead/action-wait-for-check/releases/tag/v1.2.0)

**Pull request merged**
